--- !ruby/object:Container::Memento
cont_user_id: 22013
container_name: ivpn
ctype: service
publisher_namespace: EnginesSystem
type_path: vpn/ivpn
persistent: true
capabilities: all
privileged: true
last_error: 
memory: '96'
hostname: ivpn
domain_name: 
environments: 
kerberos: true
image: _Engines_System(flavor)/ivpn:_Engines_System(release)
volumes: 
port: 
mapped_ports:
 nat-t:
  name: nat-t
  port: 4500
  publicFacing: true
  external: 4500
  proto_type: udp
 ike: 
  name: ike
  port: 500
  proto_type: udp
  publicFacing: true
  external: 500
repo: na
last_result: 
set_state: nocontainer
conf_register_site: false
conf_register_dns: true
conf_zero_conf: false
conf_self_start: true
dependant_on:
- "dns"
- "syslog"
