--- !ruby/object:ManagedService
container_name: imap
publisher_namespace: EnginesSystem
type_path: imap
ctype: service
persistent: true
last_error: 
memory: '192'
hostname: imap
domain_name: 
kerberos: true
environments:
- !ruby/object:EnvironmentVariable
 name: ContUser
 value: root
 setatrun: false
image: _Engines_System(flavor)/imap:_Engines_System(release)
port: 
volumes:
 imap_data: 
  name: imap_data
  remotepath: "/var/lib/dovecot"
  localpath: "/var/lib/engines/services/imap/lib"
  permissions: "rw"
 mail_dir: 
  name: mail_dir
  remotepath: "/var/mail"
  localpath: "/var/lib/engines/services/imap/mail"
  permissions: "rw"
mapped_ports:
 imap: 
  name: imap
  port: 10143
  publicFacing: true
  external: 143
 pop3s: 
  name: pop3s
  port: 10995
  publicFacing: true
  external: 995
 imaps: 
  name: imaps
  port: 10993
  publicFacing: true
  external: 993
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_zero_conf: true
conf_self_start: true
dependant_on:
- "dns"
- "mysql_server"
- "syslog"
- "email"