--- !ruby/object:ManagedService
container_name: imap
publisher_namespace: EnginesSystem
type_path: imap
ctype: service
persistant: true
last_error: 
memory: '90'
hostname: imap
domain_name: 
environments:
- !ruby/object:EnvironmentVariable
 name: ContUser
 value: root
 setatrun: false
image: engines/imap:alpha
port: 
volumes:
 imap_data: !ruby/object:Volume
  name: imap_data
  remotepath: "/var/lib/dovecot"
  localpath: "/var/lib/engines/imap/lib"
  mapping_permissions: "rw"
 mail_dir: !ruby/object:Volume
  name: mail_dir
  remotepath: "/var/mail"
  localpath: "/var/lib/engines/imap/mail"
  mapping_permissions: "rw"
 ssl_dir: !ruby/object:Volume
  name: ssl_dir
  remotepath: "/etc/ssl"
  localpath: "/opt/engines/etc/ssl/imap"
  mapping_permissions: "ro"
eports:
- !ruby/object:WorkPort
  name: imap
  port: 10143
  publicFacing: true
  external: 143
- !ruby/object:WorkPort
  name: pop3s
  port: 10995
  publicFacing: true
  external: 995
- !ruby/object:WorkPort
  name: imaps
  port: 10993
  publicFacing: true
  external: 993
repo: na
last_result: 
setState: stopped
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true
dependant_on:
- "dns"
- "mysql_server"
- "syslog"
- "email"