--- !ruby/object:ManagedService
containerName: imap
ctype: service
persistant: true
last_error: 
memory: '90'
hostName: email
domainName: 
environments:
- !ruby/object:EnvironmentVariable
 name: ContUser
 value: root
 setatrun: false
image: engines/imap
port: 
eports:
- !ruby/object:WorkPort
  name: imap
  port: 143
  publicFacing: true
  external: 143
- !ruby/object:WorkPort
  name: pop3s
  port: 995
  publicFacing: true
  external: 995
- !ruby/object:WorkPort
  name: imaps
  port: 993
  publicFacing: true
  external: 993

repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: running
nginxored: false
databases: []
conf_register_site: true
conf_register_dns: true