

#state=`echo $TZ |cut -f2 -d/`
#country=`echo $TZ |cut -f1 -d/`
#TZ="$country\/$state"

#USER 0
#RUN cat /etc/apache2/sites-enabled/000-default.conf  | sed "s/^#SERVER_NAME/ ServerName $fqdn/" > /tmp/.000-default.conf;\ 
#	cp /tmp/.000-default.conf  /etc/apache2/sites-enabled/000-default.conf;\
#	echo  ServerName $fqdn > /tmp/apache2.conf;\
#	cat /etc/apache2/apache2.conf >> /tmp/apache2.conf;\
#	mv /tmp/apache2.conf /etc/apache2/apache2.conf

#JDBC this some how? or drop	
ENV DATABASE_URL mysql2://$dbuser:$dbpasswd@$dbhost/$dbname


#USER $ContUser