



#after chmod so protected
ADD home/start.bash /home/start.bash

RUN chown -R www-data /usr/share/tomcat7/work/Catalina/localhost/
	
USER www-data


VOLUME /var/log/
WORKDIR /home/app
CMD ["/home/start.bash"]


