

RUN groupadd -g $data_gid writegrp;\
	usermod -a -G $data_gid www-data;\
	chown -R  $data_uid.$data_gid  /home/app/ /home/local/;\
	mkdir  -p /var/log/apache2/ ; chown www-data /var/log/apache2/ ;\
	mkdir  -p /run/apache2/ ; chown www-data /run/apache2/

#after chmod so protected
ADD home/start.bash /home/start.bash

RUN chown -R www-data /usr/share/tomcat7/work/Catalina/localhost/
	
USER www-data


VOLUME /var/log/
WORKDIR /home/app
CMD ["/home/start.bash"]


