--- !ruby/object:ManagedService
container_name: sumologic_syslog
publisher_namespace: SumoLogic
type_path: syslog
ctype: service
persistent: false
last_error: 
memory: '32'
hostname: syslog
domain_name: 
environments: []
image: sumologic/collector:latest-syslog
arguments:
  - 'su3YGbWw7JmBA6'
  - 'kzwfDzHXPhrYFOp2qsG7f1eL61fSiqscIg5BnZs7zj8WET3b8zYA70VjPxz9cAxv'
port: 
mapped_ports:
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"