FROM  engines/passenger:_System(release)

ADD home home
ADD engines home/engines


RUN chown 2666 `find /var /usr/share /usr/local /home -user ruby`;\
 /usr/sbin/usermod -u 2666 ruby

ENV ContUser ruby
ENV RAILS_ENV production
EXPOSE 3000



#Built as
#_Builder(container_name)
#_Builder(domain_name)
#_Builder(hostname)
#_Builder(http_protocol)
#_Builder(repoName)
#_Builder(webPort)
#_Builder(build_name)
#_Builder(runtime)
#_Builder(set_environments) 
#_Builder(environments)

     