

WORKDIR /home/app
USER 0
#lock down gems Do I need to ? Long process

RUN chown -R root /usr/local/rbenv/versions/$ruby_version/;\
\
	groupadd -g $data_gid writegrp;\
	usermod -G $data_gid www-data;\
	chown -R  $data_uid.$data_gid  ./;\
\
	mkdir -p app/tmp/ public/cache/ public/assets /run/apache2;\
	chown www-data.$data_gid app/tmp/ public/assets public/cache/ /run/apache2;\
\
	chmod -R g+w log  app/assets;\
	chmod g+w db


#after chmod so protected
ADD Rack.sh /home/app/

USER www-data
##############
### Must disable ruby login
###

	
VOLUME /var/log/
WORKDIR /home/app
#CMD /home/app/Rack.sh
CMD /home/start.bash


