--- !ruby/object:ManagedService
containerName: cAdvisor
ctype: service
last_error: 
memory: '128'
hostName: cadvisor
domainName: enginesos.jvodan.com
environments: []
image: google/cadvisor:latest
volumes:
- !ruby/object:Volume
  name: var/run
  remotepath: "/var/run"
  localpath: "/var/run"
  vol_permissions: "rw"
- !ruby/object:Volume
  name: lib/docker
  remotepath: "/var/lib/docker"
  localpath: "/var/lib/docker"
  vol_permissions: "rw"
- !ruby/object:Volume
  name: sys
  remotepath: "/sys/"
  localpath: "/sys/"
  vol_permissions: "ro"
port: 8080
eports: []
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: nocontainer
nginxored: false
databases: []
conf_register_site: true
conf_register_dns: true
conf_self_start: true