#/containers/service/container_name
#/containers/service/container_name/recreate
#/containers/service/container_name/stop
#/containers/service/container_name/start
#/containers/service/container_name/pause
#/containers/service/container_name/unpause
#/containers/service/container_name/destroy
#/containers/service/container_name/create
#/containers/service/container_name/restart
#