

USER 0
#protect source
RUN groupadd -g $data_gid writegrp;\
	usermod -G $data_gid www-data;\
	chown -R  $data_uid.$data_gid  /home/app/

USER 2671
ADD home/start.bash home/start.bash
WORKDIR /home/app

	 



