--- !ruby/object:DBManagedService
containerName: mysql_server
ctype: service
persistant: false
last_error: 
memory: '128'
hostName: mysql
domainName: 
environments: 
image: engines/mysql
volumes:
 my_database: !ruby/object:Volume
  name: my_database
  remotepath: "/var/lib/mysql"
  localpath: "/var/lib/engines/mysql"
  mapping_permissions: "rw"
 mysql_run: !ruby/object:Volume
  name: mysql_run
  remotepath: "/var/run/mysqld/"
  localpath: "/opt/engines/run/services/mysql_server/run/mysqld"
  mapping_permissions: "rw"  
port: 
eports:
- !ruby/object:WorkPort
  name: mysql
  port: 3306
  publicFacing: false
  external: 0
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true

