--- !ruby/object:ManagedService
container_name: mysql_server
publisher_namespace: EnginesSystem
type_path: database/sql/mysql
ctype: service
persistent: true
last_error: 
memory: '456'
stop_timeout: 500
hostname: mysql
domain_name: 
environments: []
image: engines/mysql:_Engines_System(release)
volumes:
 my_database: 
  name: my_database
  remotepath: "/var/lib/mysql"
  localpath: "/var/lib/engines/mysql"
  permissions: "rw"
 sslcerts: 
  name: sslcerts
  remotepath: "/etc/ssl/"
  localpath: "/var/lib/engines/cert_auth/services/mysql/"
  permissions: "ro"  
 mysql_run: 
  name: mysql_run
  remotepath: "/var/run/mysqld/"
  localpath: "/opt/engines/run/services/mysql_server/run/mysqld"
  permissions: "rw"  
port: 
mapped_ports:
 mysql: 
  name: mysql
  port: 3306
  publicFacing: false
  external: 0
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"
