VOLUME /var/log/

RUN  mkdir -p  /var/www/ ;\
	 ln -s /home/app /var/www/html/

ADD home/start.sh /home/engines/scripts/startup/start.sh

USER $ContUser

CMD [/home/engines/scripts/startup/start.sh"]


