FROM  engines/php:_Engines_System(release)
ADD home home
ADD engines home/engines
ENV CONTFSVolHome /home/fs/
ENV ContUser www-data

RUN	apt-get update -y;\
	if [ -f /home/engines/configs/php/71-custom.ini ] ;\
		then		\
		mkdir -p /etc/php5/apache2/conf.d/;\
			cp /home/engines/configs/php/71-custom.ini /etc/php5/apache2/conf.d/;\
	fi;\
	if [ -f /home/engines/configs/apache2/extra.conf ] ;\
		then \
			mkdir -p /etc/apache2/conf.d/;\
			cp /home/engines/configs/apache2/extra.conf /etc/apache2/conf.d/;\
	fi	;\
	if [ -f /home/engines/configs/apache2/site.conf ] ;\
		then\
		mkdir -p /etc/apache2/sites-enabled/000-default.conf;\
			cp /home/engines/configs/apache2/site.conf /etc/apache2/sites-enabled/000-default.conf;\
	fi

	

CMD /home/start.bash



