--- !ruby/object:ManagedService
containerName: smtp
ctype: service
last_error: 
memory: '32'
hostName: smtp
domainName: 
environments: []
image: engines/smtp
volumes: 
port: 
eports: []
repo: na
last_result: |
  nginx
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true

