--- !ruby/object:ManagedService
container_name: smtp
publisher_namespace: EnginesSystem
type_path: smtp
ctype: service
persistent: true
last_error: 
memory: '32'
hostname: smtp
domain_name: 
environments: []
image: engines/smtp:_Engines_System(release)
volumes: 
 ssl_dir: !ruby/object:Volume
  name: ssl_dir
  remotepath: "/etc/ssl"
  localpath: "/opt/engines/etc/smtp/ssl"
  mapping_permissions: "ro"
port: 
mapped_ports: 
- !ruby/object:WorkPort
  name: smtp
  port: 465
  publicFacing: true
  external: 465
- !ruby/object:WorkPort
  name: subs_smtp
  port: 587
  publicFacing: true
  external: 587
repo: na
last_result:
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_zero_conf: true
conf_self_start: true
dependant_on:
- "dns"
- "syslog"