--- !ruby/object:ManagedService
container_name: smtp
publisher_namespace: EnginesSystem
type_path: smtp
ctype: service
persistant: true
last_error: 
memory: '32'
hostname: smtp
domain_name: 
environments: []
image: engines/smtp:alpha
volumes: 
 ssl_dir: !ruby/object:Volume
  name: ssl_dir
  remotepath: "/etc/ssl"
  localpath: "/opt/engines/etc/ssl/smtp"
  mapping_permissions: "ro"
port: 
eports: 
- !ruby/object:WorkPort
  name: smtp
  port: 465
  publicFacing: true
  external: 465
repo: na
last_result:
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"
- "syslog"