--- !ruby/object:ManagedService
cont_user_id: 22019
container_name: samba
ctype: service
publisher_namespace: EnginesSystem
type_path: filesystem/service/samba
persistent: true
last_error: 
memory: '156'
hostname: samba
domain_name: 
environments: []
kerberos: true
image: _Engines_System(flavor)/samba:_Engines_System(release)
volumes:
 fs_rw: 
  name: fs_rw
  remotepath: "/rw/"
  localpath: "/var/lib/engines/apps/"
  permissions: "rw"
 fs_ro: 
  name: fs_ro
  remotepath: "/ro/"
  localpath: "/var/lib/engines/apps/"
  permissions: "ro"
 homes: 
  name: homes
  remotepath: "/home/users/"
  localpath: "/var/lib/engines/home/"
  permissions: "rw" 
port: 
mapped_ports:
 microsoft-ds: 
  name: microsoft-ds
  port: 445
  publicFacing: true
  proto_type: tcp
  external: 445
 netbios-ns: 
  name: netbios-ns
  proto_type: both
  port: 137
  publicFacing: true
  external: 137
 netbios-ssn: 
  name: netbios-ssn
  proto_type: both
  port: 139
  publicFacing: true
  external: 139
 netbios-dgm: 
  name: netbios-dgm
  proto_type: both
  port: 138
  publicFacing: true
  external: 138
repo: na
last_result: 
setState: running
conf_register_site: false
conf_register_dns: true
conf_zero_conf: true
conf_self_start: true
dependant_on:
- "dns"
- "ldap"
- "syslog"
