--- !ruby/object:DNSService
containerName: dns
ctype: service
conf_self_start: false
last_error: 
memory: '42'
hostName: dns
domainName: 
environments:
- !ruby/object:EnvironmentVariable
 name: ContUser
 value: bind
 setatrun: false
image: engines/dns
volumes: 
 configuration: !ruby/object:Volume
  name: configuration
  remotepath: "/etc/bind/engines"
  localpath: "/opt/engines/etc/dns/config"
  mapping_permissions: "ro"
 var_run: !ruby/object:Volume
  name: "var_run"
  remotepath: "/var/run/"
  localpath: "/opt/engines/run/services/dns/run/dns"
  mapping_permissions: "rw" 
eports:
- !ruby/object:WorkPort
  name: dns
  port: 53
  publicFacing: true
  proto_type: udp
  external: 53
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true