--- !ruby/object:ManagedService
container_name: dns
publisher_namespace: EnginesSystem
type_path: dns
ctype: service
persistent: false
conf_self_start: true
last_error: 
memory: '96'
hostname: dns
domain_name: 
environments: []
image: _Engines_System(flavor)/dns:_Engines_System(release)
volumes: 
 ip_details: 
  name: ip_details
  remotepath: "/opt/engines/etc/net/"
  localpath: "/opt/engines/etc/net/"
  permissions: "ro"
mapped_ports:
 dns:
  name: dns
  port: 53
  publicFacing: true
  proto_type: udp
  external: 53
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: false