--- !ruby/object:ManagedService
container_name: dns
publisher_namespace: EnginesSystem
type_path: dns
ctype: service
persistant: false
conf_self_start: true
last_error: 
memory: '96'
hostname: dns
domain_name: 
environments: []
image: engines/dns:_Engines_System(release)
volumes: 
 ip_details: !ruby/object:Volume
  name: ip_details
  remotepath: "/home/net/"
  localpath: "/opt/engines/etc/net/"
  mapping_permissions: "ro"
 configuration: !ruby/object:Volume
  name: configuration
  remotepath: "/etc/bind/engines"
  localpath: "/opt/engines/etc/dns/config"
  mapping_permissions: "ro"
 var_run: !ruby/object:Volume
  name: "var_run"
  remotepath: "/var/run/"
  localpath: "/opt/engines/run/services/dns/run/dns"
  mapping_permissions: "rw" 
mapped_ports:
- !ruby/object:WorkPort
  name: dns
  port: 53
  publicFacing: true
  proto_type: udp
  external: 53
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true