--- !ruby/object:ManagedService
container_name: cAdvisor
ctype: service
last_error: 
memory: '100'
hostname: cadvisor
environments: []
image: google/cadvisor:latest
volumes:
 var_run: 
  name: var_run
  remotepath: "/var/run"
  localpath: "/var/run"
  permissions: "rw"
 lib_docker: 
  name: lib_docker
  remotepath: "/var/lib/docker"
  localpath: "/var/lib/docker"
  vol_permissions: "rw"
 system_path: 
  name: system_path
  remotepath: "/sys/"
  localpath: "/sys/"
  permissions: "ro"
port: 8080
eports: []
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: nocontainer
nginxored: false
conf_register_site: true
conf_register_dns: true
conf_self_start: true
setState: nocontainer
dependant_on:
- "dns"
- "nginx"