--- !ruby/object:MongoDBService
containerName: mongo_server
ctype: service
persistant: true
last_error: 
memory: '128'
hostName: mongo
domainName: 
environments: 
image: engines/mongo
volumes:
 mg_database: !ruby/object:Volume
  name: mg_database
  remotepath: "/data/db/"
  localpath: "/var/lib/engines/mongo"
  mapping_permissions: "rw"
port: 
eports:
- !ruby/object:WorkPort
  name: mongo
  port: 3306
  publicFacing: false
  external: 0
repo: na
last_result: |
   rf
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true