--- !ruby/object:ManagedService
container_name: mongo_server
ctype: service
publisher_namespace: EnginesSystem
type_path: database/nosql/mongo
persistant: true
last_error: 
memory: '128'
hostname: mongo
domain_name: 
environments: []
image: engines/mongo:_Engines_System(release)
volumes:
 mg_database: !ruby/object:Volume
  name: mg_database
  remotepath: "/data/db/"
  localpath: "/var/lib/engines/mongo"
  mapping_permissions: "rw"
port: 
eports:
- !ruby/object:WorkPort
  name: mongo
  port: 27017
  publicFacing: false
  external: 0
- !ruby/object:WorkPort
  name: mongoweb
  port: 28017
  publicFacing: false
  external: 0
repo: na
last_result: 
setState: stopped
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"