FROM  engines/shiny:_Engines_System(release)

ENV ContUser rstudio
ENV CONTFSVolHome /home/fs/

ADD build_scripts /build_scripts
ADD home home
ADD engines home/engines

RUN	apt-get update -y &&\
	usermod -G containers -a www-data  &&\
	chown $ContUser /opt $HOME

