FROM  engines/meteor:_Engines_System(release)
ADD build_scripts /build_scripts
ADD home home
ENV CONTFSVolHome /home/fs/
ADD engines home/engines
ENV ContUser node

RUN apt-get update;\
	chown $ContUser /opt



