--- !ruby/object:ManagedService
container_name: openid
ctype: service
persistent: true
last_error: 
memory: '90'
hostname: openid
publisher_namespace: EnginesSystem
type_path: openid
port: 8000
kerberos: true
volumes:
 openid:
  name: openid
  remotepath: "/var/lib/openid/"
  localpath: "/var/lib/engines/services/openid/"
  permissions: "rw"
environments:
- !ruby/object:EnvironmentVariable
 name: DEFAULT_DOMAIN
 value: _Engines_System(default_domain)
 has_changed: true
 build_time_only: true
image: _Engines_System(flavor)/openid:_Engines_System(release)
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: true
conf_register_dns: true
conf_self_start: true
dependant_on:
- "ldap"
- "wap"