--- !ruby/object:ManagedService
cont_user_id: 22012
container_name: wwwstats
publisher_namespace: SumoLogic
type_path: wwwstats
ctype: service
persistent: true
last_error: 
memory: '268'
hostname: wwwstats
domain_name: 
environments: []
image: _Engines_System(flavor)/sumologic-wwwstats:_Engines_System(release)
volumes:
 config: 
  name: weblogs
  remotepath: "/var/log/www/"
  localpath: "/var/log/engines/services/wap/nginx/"
  permissions: ro
port: 
mapped_ports:
repo: na
last_result: 
setState: nocontainer
conf_register_site: false
conf_register_dns: false
conf_self_start: true
dependant_on:

