--- !ruby/object:SystemService
container_name: registry
ctype: system_service
consumer_less: true
persistent: true
conf_self_start: true
publisher_namespace: EnginesSystem
type_path: registry
last_error: 
memory: '200'
hostname: registry
domain_name: 
environments: []
image: _Engines_System(flavor)/registry:_Engines_System(release)
volumes:
 docker_bin: 
  name: registry_dir
  remotepath: "/opt/engines/run/service_manager/"
  localpath: "/var/lib/engines/registry"
  permissions: rw
port: 
mapped_ports: 
repo: na
last_result: 
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: false
dependant_on: