--- !ruby/object:SystemService
container_name: registry
ctype: system_service
persistant: false
conf_self_start: true
publisher_namespace: EnginesSystem
type_path: registry
last_error: 
memory: '96'
hostname: registry
domain_name: 
environments: []
image: engines/registry:_Engines_System(release)
volumes:
 docker_bin: !ruby/object:Volume
  name: registry_dir
  remotepath: "/opt/engines/run/service_manager/"
  localpath: "/var/lib/engines/registry"
  mapping_permissions: rw
port: 
eports:
repo: na
last_result: 
setState: running
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: false
dependant_on: