#require_relative 'auth/routes.rb'
require_relative 'containers/routes.rb'
require_relative 'registry/registry.rb'
require_relative 'service_manager/routes.rb'
require_relative 'system/routes.rb'
require_relative 'engine_builder/engine_builder.rb'
require_relative '404.rb'
