--- !ruby/object:Container::Memento
container_name: wwwstats
publisher_namespace: EnginesSystem
type_path: wwwstats
ctype: service
persistent: true
last_error: 
memory: '48'
hostname: wwwstats
domain_name: 
environments: []
image: _Engines_System(flavor)/wwwstats:_Engines_System(release)
volumes:
 config: 
  name: weblogs
  remotepath: "/var/log/www/"
  localpath: "/var/log/engines/services/wap/nginx/"
  permissions: ro
port: 
mapped_ports:
repo: na
last_result: 
set_state: nocontainer
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"
- "wap"
