WORKDIR /home/app
VOLUME /var/log/
RUN ln -s /home/app /var/www
#do this after chmods and chowns
ADD home/start.bash /home/start.bash
RUN /home/post_build_clean.sh
USER $ContUser
CMD ["/home/start.bash"]

