WORKDIR /home/app

VOLUME /var/log/


RUN  mkdir -p  /var/www/ ;\
	 ln -s /home/app /var/www/html/


ADD home/start.bash /home/start.bash

RUN /home/post_build_clean.sh 
	

USER $ContUser

CMD ["/home/start.bash"]

