FROM  engines/tomcat8:_Engines_System(release)
ADD build_scripts /build_scripts
ADD home home
ENV ContUser www-data
ENV CONTFSVolHome /home/fs/
ADD engines home/engines
#ADD home/app/webapps/ /usr/share/tomcat7/webapps
RUN apt-get update;\
	chown 22671  /usr/share/tomcat7/webapps  `find /var /usr/share /usr/local /home -user www-data`;\
	/usr/sbin/usermod -u 22671 www-data;\
	mkdir -p /home/app/webapps/ ;\
	rm -r /usr/share/tomcat7/webapps;\
	ln -s /home/app/webapps /usr/share/tomcat7/;\
	chmod g+w /home/app/webapps/	;\
	mkdir -p /usr/share/tomcat7/work/Catalina/localhost/ ;\
	chown www-data -R /usr/share/tomcat7/work/ ;\
	usermod -a -G tomcat  www-data ;\
	usermod -a -G data-user www-data ;\
  chown $ContUser /opt	
  