--- !ruby/object:ManagedService
container_name: ldap
publisher_namespace: EnginesSystem
type_path: ldap
ctype: service
persistent: true
conf_self_start: true
last_error: 
memory: '128'
hostname: ldap
domain_name: engines.local
host_network: false
soft_service: false
environments: []
image: engines/ldap:_Engines_System(release)
volumes: 
 configuration: 
  name: ip_file
  remotepath: "/home/net/"
  localpath: "/opt/engines/etc/net/"
  permissions: "ro"
 ldap_db: 
  name: ldap_db
  remotepath: "/var/lib/ldap/"
  localpath: "/var/lib/engines/ldap/"
  permissions: "rw"
 ldap_etc: 
  name: ldap_key
  remotepath: "/etc/krb5kdc/keys/"
  localpath: "/var/lib/engines/auth/etc/krb5kdc/ldap/"
  permissions: "rw"
mapped_ports:
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: true

