--- !ruby/object:Container::Memento
cont_user_id: 22030
container_name: ldap
publisher_namespace: EnginesSystem
type_path: ldap
ctype: service
persistent: true
conf_self_start: true
shareable: false
last_error: 
memory: '128'
hostname: ldap
domain_name: engines.internal
host_network: false
soft_service: false
environments: []
kerberos: true
mapped_ports:
 ldap:
  name: ldap
  port: 389
  publicFacing: false
  external: 389
image: _Engines_System(flavor)/ldap:_Engines_System(release)
volumes: 
 ldap_db: 
  name: ldap_db
  remotepath: "/var/lib/ldap/"
  localpath: "/var/lib/engines/services/ldap/lib"
  permissions: "rw"
 ldap_conf: 
  name: slapd_conf
  remotepath: "/etc/ldap/slapd.d"
  localpath: "/var/lib/engines/services/ldap/slapd.d"
  permissions: "rw"
environments: []
repo: na
last_result: 
set_state: running
conf_register_site: false
conf_register_dns: true
dependant_on:
- "auth"


