#!/bin/sh 

mysqldump  --all-databases > /local_backup_dests/tmp/db.sql
mkdir /local_backup_dests/tmp/
cp -rp /backup_src/engines/opt/engines/etc /local_backup_dests/tmp/
cp -rp /backup_src/engines/opt/engines/run /local_backup_dests/tmp/
cp -rp /backup_src/engines/home/engines/db /local_backup_dests/tmp/

