#!/bin/sh 
mkdir /home/backup/tmp
mysqldump  h mysql.engines.internal --all-databases > /home/backup/tmp/db.sql

cp -rp /backup_src/engines/etc /home/backup/tmp/
cp -rp /backup_src/engines/run /home/backup/tmp/

#have to do this to skip any read errors from above
echo ok
