
USER 0
RUN apt-get -y remove  build-essential gcc make ;\
	apt-get -y clean 
#protect source

 
ADD home/start.bash home/start.bash
USER www-data

#do this after chmods and chowns

WORKDIR /home/app

	 



