FROM  engines/frameworkbuild:_Engines_System(release)

ENV CONTFSVolHome /home/fs/
ENV ContUser www-data

ADD build_scripts /build_scripts
ADD home home
ADD engines home/engines


RUN	apt-get update -y &&\
	/usr/sbin/usermod -u 22671 www-data &&\
	usermod -G containers -a www-data &&\
	chown $ContUser /opt $HOME
	




