
RUN apt-get -y remove  build-essential gcc make ;\
	apt-get -y clean 
#protect source
RUN mkdir  -p /var/log/apache2/ ; chown www-data /var/log/apache2/ ;\
	mkdir  -p /run/apache2/ ; chown www-data /run/apache2/
 
ADD home/start.bash home/start.bash
USER www-data

#do this after chmods and chowns

WORKDIR /home/app

	 



