--- !ruby/object:ManagedService
container_name: avahi
publisher_namespace: EnginesSystem
type_path: avahi
ctype: service
persistent: false
conf_self_start: true
last_error: 
memory: '32'
hostname: avahi
domain_name: local
host_network: true
soft_service: true
kerberos: false
environments: []
image: _Engines_System(flavor)/avahi:_Engines_System(release)
volumes: 
 configuration: 
  name: ip_file
  remotepath: "/home/net/"
  localpath: "/opt/engines/etc/net/"
  permissions: "ro"
mapped_ports:
 mdns:
  name: mdns
  port: 5353
  publicFacing: true
  proto_type: udp
  external: 5353
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: false

