--- !ruby/object:ManagedService
container_name: avahi
publisher_namespace: EnginesSystem
type_path: avahi
ctype: service
persistent: false
conf_self_start: true
last_error: 
memory: '32'
hostname: avahi
domain_name: local
host_network: true
soft_service: true
environments: []
image: engines/avahi:_Engines_System(release)
volumes: 
 configuration: !ruby/object:Volume
  name: ip_file
  remotepath: "/home/net/"
  localpath: "/opt/engines/etc/net/"
  mapping_permissions: "ro"
mapped_ports:
- !ruby/object:WorkPort
  name: mdns
  port: 5353
  publicFacing: true
  proto_type: udp
  external: 5353
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: false

