FROM  engines/node10:_Engines_System(release)

ENV CONTFSVolHome /home/fs/
ENV ContUser node

ADD build_scripts /build_scripts
ADD home home
ADD engines home/engines

RUN apt-get update -y &&\
	chown 22673 `find /var /usr/share /usr/local /home -user node` &&\ 
	 /usr/sbin/usermod -u 22673 node &&\
	 mkdir -p  /home/home_dir/.npm &&\
	 chown $ContUser /opt /home/home_dir/.npm

