
ENV ContUser www-data

 
WORKDIR /home/app
VOLUME /var/log/
RUN ln -s /home/app /var/www
#do this after chmods and chowns
ADD home/start.bash /home/start.bash ;\
    usermod -G data-user -a www-data
USER $ContUser
CMD ["/home/start.bash"]




