FROM  engines/ngpassenger:_Engines_System(release)

ENV CONTFSVolHome /home/fs/
ENV WWW_DIR public
ENV ContUser ruby
ENV RAILS_ENV production

#ENV SECRET_KEY_BASE	_Engines_System(random(128))
ENV RAILS_MASTER_KEY _Engines_System(random(128))
ENV PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

ADD build_scripts /build_scripts
ADD home home
ADD engines home/engines

RUN apt-get update &&\
	chown $ContUser /opt
	