WORKDIR /home/app

USER 0

ENV DATABASE_URL $rails_flavor://$dbuser:$dbpasswd@$dbhost/$dbname

RUN /build_scripts/configure_nginx.sh &&\
	/build_scripts/create_database_yml.sh &&\
	mkdir -p /home/app/.bundle/ ;\
	chown -R $ContUser /home/app/.bundle/
	
USER $ContUser

RUN bash /home/setup.sh &&\
  	/build_scripts/run_bundler.sh
