--- !ruby/object:ManagedService
container_name: logrotate
publisher_namespace: EnginesSystem
type_path: logrotate
ctype: service
service_type: transient
soft_service: true
persistent: false
last_error: 
memory: '32'
hostname: logrotate
domain_name: 
kerberos: false
environments: []
image: _Engines_System(flavor)/logrotate:_Engines_System(release)
volumes:
 syslog: 
  name: syslog
  remotepath: "/var/log/syslog/"
  localpath: "/var/lib/engines/services/syslog/rmt/"
  permissions: rw
 engines: 
  name: engines
  remotepath: "/var/log/engines/engines/"
  localpath: "/var/log/engines/containers/"
  permissions: rw
 services: 
  name: services
  remotepath: "/var/log/engines/services/"
  localpath: "/var/log/engines/services/"
  permissions: rw
 system_services: 
  name: system_services
  remotepath: "/var/log/engines/system_services/"
  localpath: "/var/log/engines/system_services/"
  permissions: rw
port: 
mapped_ports:
repo: na
last_result: 
setState: stopped
nginxored: false
conf_register_site: false
conf_register_dns: false
conf_self_start: true
dependant_on: []