FROM  engines/node:_Engines_System(release)
ADD build_scripts /build_scripts
ADD home home
ENV CONTFSVolHome /home/fs/
ADD engines home/engines
ENV ContUser node
RUN chown 22673 `find /var /usr/share /usr/local /home -user node`
RUN /usr/sbin/usermod -u 22673 node
RUN  chown $ContUser /opt


