FROM  engines/rails3:$release

ADD home home
ADD engines home/engines

#CMD cd /home/app ; gem install bundle; env PORT=3000 sh  Procfile.sh

EXPOSE 3000

RUN chown 2667 `find /var /usr/share /usr/local /home -user ruby`
RUN /usr/sbin/usermod -u 2668 ruby

