FROM ubuntu



RUN apt-get -y  --force-yes update
RUN apt-get -y  --force-yes upgrade


RUN apt-get -y install sudo sendmail-bin unzip  mysql-client openssh-server  vim curl dnsutils git libmysqlclient-dev wget bzip2 zlibc
RUN mkdir -p /var/run



ADD ddns.key /etc/
ADD ddns.private /etc/
ADD dns-init.sh /home/
ADD init.sh /home/
ADD _init.sh /home/

CMD /bin/bash /home/init.sh


