--- !ruby/object:SoftwareServiceDefinition
accepts:
- !ruby/object:String  
  "ManagedEngine"
author: Engines
title: Database
description: "Database "
service_provider: database
service_type: database
dedicated: false
persistant: true
image_name: engines/volmanager
consumer_params:
setup_params:
   database_host:
    name: database_host
    title: database_host
    regexverifer: ".*"
    tooltip: " "
    type: "string"
    hint: " "
    placeholder: " "
    required: true
    default_value: " "
    comment: " "
   database_name:
    name: database_name
    title: folder
    regexverifer: ".*"
    tooltip: " "
    type: "string"
    hint: " "
    placeholder: " "
    required: true
    default_value: " "
    comment: " "
  username:
    name: dbusername
    title: DB User Name
    regexverifer: ".*"
    tooltip: " "
    type: "string"
    hint: " "
    placeholder: " "
    required: true
    default_value: " " 
    comment: " "
  password:
    name: dbpassword
    title: DB Password
    tooltip: " "
    type: "password"
    hint: " "
    placeholder: " "
    required: true
    default_value: " "
    comment: " "