--- !ruby/object:SoftwareServiceDefinition
accepts: 
- !ruby/object:String  
 "ManagedEngine"
author: Engines
title: Database
description: "Database "
service_provider: database
service_type: database
dedicated: false
persistant: true
image_name: engines/volmanager
consumer_params:
setup_params:
  database_host:
   name: database_host
   label: database_host
   regex_validator: ".*"
   tooltip: "Local or the ip address/hostname of the database server"
   type: "text_field"
   hint: " "
   placeholder: " "
   required: true
   value: " "
   comment: " "
  database_name:
   name: database_name
   label: folder
   regex_validator: ".*"
   tooltip: " "
   type: "text_field"
   hint: " "
   placeholder: " "
   required: true
   value: " "
   comment: " "
 username:
   name: dbusername
   label: DB User Name
   regex_validator: ".*"
   tooltip: " "
   type: "text_field"
   hint: " "
   placeholder: " "
   required: true
   value: " " 
   comment: " "
 password:
   name: dbpassword
   label: DB Password
   tooltip: " "
   type: password_with_confirmation
   hint: " "
   placeholder: " "
   required: true
   value: " "
   comment: " "
   regex_validator: ".*"