--- !ruby/object:ManagedService
container_name: ftp
ctype: service
publisher_namespace: EnginesSystem
type_path: filesystem/service/ftp
persistant: true
last_error: 
memory: '56'
hostname: ftp
domain_name: 
environments: []
image: engines/ftp:_Engines_System(release)
volumes:
 ssl_certs: !ruby/object:Volume
  name: ssl_certs
  remotepath: "/etc/ssl/"
  localpath: "/opt/engines/etc/ftp/ssl/"
  mapping_permissions: "ro"
 fs_rw: !ruby/object:Volume
  name: fs_rw
  remotepath: "/ftp/rw/"
  localpath: "/var/lib/engines/fs/"
  mapping_permissions: "rw"
 fs_ro: !ruby/object:Volume
  name: fs_ro
  remotepath: "/ftp/ro/"
  localpath: "/var/lib/engines/fs/"
  mapping_permissions: "rw"
port: 
mapped_ports:
- !ruby/object:WorkPort
  name: ftp
  port: 21
  publicFacing: true
  external: 21
- !ruby/object:WorkPort
  name: ftp-data
  port: 20
  publicFacing: true
  external: 20
- !ruby/object:WorkPort
  name: ftps
  port: 989
  publicFacing: true
  external: 989
- !ruby/object:WorkPort
  name: ftps-data
  port: 990
  publicFacing: true
  external: 990
- !ruby/object:WorkPort
  name: sftp
  port: 115
  publicFacing: true
  external: 115
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_zero_conf: true
conf_self_start: true
dependant_on:
- "dns"
- "auth"
- "syslog"
