--- !ruby/object:ManagedService
container_name: ftp
ctype: service
publisher_namespace: EnginesSystem
type_path: filesystem/service/ftp
persistent: true
last_error: 
memory: '56'
hostname: ftp
domain_name: 
environments: []
image: _Engines_System(flavor)ftp:_Engines_System(release)
volumes:
 ssl_certs: 
  name: ssl_certs
  remotepath: "/etc/ssl/"
  localpath: "/var/lib/engines/cert_auth/services/ftp"
  permissions: "ro"
 fs_rw: 
  name: fs_rw
  remotepath: "/ftp/rw/"
  localpath: "/var/lib/engines/fs/"
  permissions: "rw"
 kdc: 
  name: kdc
  remotepath: "/etc/krb5kdc/keys/"
  localpath: "/var/lib/engines/auth/etc/krb5kdc/ftp/"
  permissions: "rw"
 fs_ro: 
  name: fs_ro
  remotepath: "/ftp/ro/"
  localpath: "/var/lib/engines/fs/"
  permissions: "rw"
port: 
mapped_ports:
 ftp:
  name: ftp
  port: 21
  publicFacing: true
  external: 21
 ftp-data: 
  name: ftp-data
  port: 20
  publicFacing: true
  external: 20
 ftps:
  name: ftps
  port: 989
  publicFacing: true
  external: 989
 ftps-data: 
  name: ftps-data
  port: 990
  publicFacing: true
  external: 990
 sftp:
  name: sftp
  port: 115
  publicFacing: true
  external: 115
 active_ports:
  name: active_ports
  port: "49900-50000"
  publicFacing: true
  external: "49900-50000"
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_zero_conf: true
conf_self_start: true
dependant_on:
- "dns"
- "auth"
- "syslog"
