FROM  engines/php:_Engines_System(release)
ENV ContUser www-data
ADD build_scripts /build_scripts
ADD home home
ADD engines home/engines
ENV CONTFSVolHome /home/fs/
RUN apt-get update;\
	chown $ContUser /opt
