

USER 0
#protect source
RUN groupadd -g $data_gid writegrp;\
	usermod -a -G $data_gid www-data;\
	chown -R  $data_uid.$data_gid  /home/app/ ;\
	ln -s /home/app /var/www
	
USER www-data
ADD home/start.bash /home/start.bash
WORKDIR /home/app

	 



