

#state=`echo $TZ |cut -f2 -d/`
#country=`echo $TZ |cut -f1 -d/`
#TZ="$country\/$state"

WORKDIR /home/app
USER 0
RUN cat /etc/apache2/sites-enabled/000-default.conf  | sed "s/^#SERVER_NAME/ ServerName $fqdn/" > /tmp/.000-default.conf;\ 
	cp /tmp/.000-default.conf  /etc/apache2/sites-enabled/000-default.conf ;\
	echo  ServerName $fqdn > /tmp/apache2.conf;\
	cat /etc/apache2/apache2.conf >> /tmp/apache2.conf;\
	mv /tmp/apache2.conf /etc/apache2/apache2.conf ;\
\
\
	if test -d config ;\
		then \
			config_dir=config;\
		else \
			config_dir=".";\
	fi ;\
	echo "login: &login" > $config_dir/database.yml;\ 
	echo "  adapter: $dbflavor" >> $config_dir/database.yml;\ 
	echo "  host: localhost">> $config_dir/database.yml;\ 
	echo "  username: root">> $config_dir/database.yml;\ 
	echo "  password:">> $config_dir/database.yml;\ 
	echo "development:" >> $config_dir/database.yml;\ 
	echo "  database: ${dbname}_dev" >> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml;\ 
	echo "test:" >> $config_dir/database.yml;\ 
	echo "  database: ${dbname}_tests" >> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml;\ 
	echo "production:">> $config_dir/database.yml;\ 
	echo "  database: $dbname ">> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml 
	

ENV DATABASE_URL $dbflavor://$dbuser:$dbpasswd@$dbhost/$dbname


USER $ContUser

RUN  if test -f Gemfile ;\
	then \
		cat /home/app/Gemfile | egrep -v "thin|puma" > /tmp/Gemfile;\
		cp /tmp/Gemfile /home/app/Gemfile;\
	 /usr/local/rbenv/shims/bundle config build.nokogiri --use-system-libraries;\
	 /usr/local/rbenv/shims/bundle --standalone install;\
	 fi  

#include custom rakes here



