WORKDIR /home/app


RUN usermod -G $data_gid www-data &&\
	chown -R  $data_uid.$data_gid  ./ &&\
\
	mkdir -p log &&\
	chmod -R g+w  log &&\
		if test -d db ;\
			then \
				chmod -R g+w  db ;\
		fi

USER www-data
##############
### Must disable ruby login
###
ADD home/start.bash /home/start.bash
	
VOLUME /var/log/

WORKDIR /home/app

CMD ["/home/start.bash"]


