FROM engines/sinatra:_Engines_System(release)

ENV CONTFSVolHome /home/fs/
ENV RACK_ENV production
ENV SECRET_KEY_BASE	_Engines_System(random(128))

ADD home home
ADD engines home/engines
ADD build_scripts /build_scripts

RUN  apt-get update -y &&\
	chown $ContUser /opt &&\
	mkdir /home/home_dir/.bundle/ &&\
	gem install bundle &&\
	chown -R $ContUser /home/home_dir/.bundle/ 
   
     