

WORKDIR /home/app
USER 0

RUN 	groupadd -g $data_gid writegrp;\
	usermod -G $data_gid www-data;\
	chown -R  $data_uid.$data_gid  ./;\
\
	mkdir -p log;\
	chmod -R g+w  log;\
		if test -d db;\
			then \
				chmod -R g+w  db;\
		fi
	


#after chmod so protected
#ADD Rack.sh /home/app/

USER www-data
##############
### Must disable ruby login
###
ADD home/start.bash /home/start.bash
	
VOLUME /var/log/
WORKDIR /home/app

CMD ["/home/start.bash"]


