WORKDIR /home/app

USER 0

RUN	if test -d config ;\
		then \
			config_dir=config;\
		else \
			config_dir=".";\
	fi ;\
	if ! test -z ${dbname} ;\
	  then \	  
	echo "login: &login" > $config_dir/database.yml;\ 
	echo "  adapter: $dbflavor" >> $config_dir/database.yml;\ 
	echo "  host: localhost">> $config_dir/database.yml;\ 
	echo "  username: root">> $config_dir/database.yml;\ 
	echo "  password:">> $config_dir/database.yml;\ 
	echo "development:" >> $config_dir/database.yml;\ 
	echo "  database: ${dbname}_dev" >> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml;\ 
	echo "test:" >> $config_dir/database.yml;\ 
	echo "  database: ${dbname}_tests" >> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml;\ 
	echo "production:">> $config_dir/database.yml;\ 
	echo "  database: $dbname ">> $config_dir/database.yml;\ 
	echo "  <<: *login" >> $config_dir/database.yml ;\
	fi 
	

ENV DATABASE_URL $dbflavor://$dbuser:$dbpasswd@$dbhost/$dbname

USER $ContUser

RUN  if test -f Gemfile ;\
	  then \
	 	bundle config build.nokogiri --use-system-libraries;\
	 	bundle --standalone install;\
	  fi  

