
FROM  engines/sinatra:_Engines_System(release)
ADD build_scripts /build_scripts
RUN	gem install bundle

ADD home home
ADD engines home/engines
ENV CONTFSVolHome /home/fs/
  

RUN  chown $ContUser /opt;\
	mkdir /home/home_dir/.bundle/;\
	chown -R $ContUser /home/home_dir/.bundle/
     